apiVersion: certificates.k8s.io/v1 

kind: CertificateSigningRequest 

metadata:  

 name: csr-for-maydarous 

spec:  

 groups:  

 - "system:authenticated" 

 usages:  

 - client auth 

 - digital signature 

 - key encipherment 

 signerName: kubernetes.io/kube-apiserver-client 

 request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1dUQ0NBVUVDQVFBd0ZERVNNQkFHQTFVRUF3d0piV0Y1WkdGeWIzVnpNSUlCSWpBTkJna3Foa2lHOXcwQgpBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFwNVc0dWhjdkYzUFl6aGlCUG1PVmhpY1ZMTEFCb0xhU0JXdDRPdzJQCnEwTnRReFVON01pNFFCNTVKdVJ1V0xJdkh0S3Mwa2RIRldDWW5CQVFuKzVJREpRZGt4ekxuRnFrR25rNzdKZ1cKN3VneWFSdGNCeENjQXpkQ2cwK0FQTnFQWkVCRXhrTXNJb3ZPTEE5V0Q5dmJYVTdFdS9hRm1DTDRSa0Ixa3pQYgo4eVl6bGZvL0J5aUk0ekhNUW1wckwySHJOUThvYzJrZWI1bFRwcTZpZHozUzVxOHJ1OUt3TTFLeEV4NDRmM0l3CnJpTytYUGhPemtYM3NWRDBLQkF6eDh0Tm8yVkFIelFWZWwyeUp3eW55cldjS2l6SlpsWDJEeG95dlpQc1FURW0KQ01hTStwZVQ2Z0N2Z0FvUW9DZjVLRmFRUUsvNzJEYzAvTnVzdW9OUVhjY2Nid0lEQVFBQm9BQXdEUVlKS29aSQpodmNOQVFFTEJRQURnZ0VCQUlURGxIWU5JYlhTSVpKNi9uOFRvK3VwQStUelhQbnpMYUxud1czVXM4VjE4cE01Cm16TzM3ZFVmVDFMdUFBM1BIQkRUcTlLZFphbmhxUnI0UEFOc2dPRWZuUlBGYU5YNzYzaWhNMndiczRTblJBNHYKa2N2MWlYN2EvTUYyRXoyOWlaSmxvemljaFVTTmNkY3RxdnRVeW9KVitBMXFZeFE1VnFmODlKbFo4TFk5dHZOegp2QTRZNW80eDNTU1h1RWFxMFIzUDA2Q0c0VWZXeDNnanA5aWQzbm5MdUZybk82WHdnQ1RER2d6ZnRwWndWbUQzCmVEQmpEYUNwVzZ4UHNLOERpbVlLRzIzQmc2djV4OWlhME1WUDhWZlpnbFcvdkVrWUg5bGpqSUVSMlRiMFNvSzIKQjhCcHJHODg1WjZKTTQ0aXdtNTd4ZnduTTRydkFqUFdtMWh1UHBNPQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K 
